### ISSUE TITLE
how to paginate?

### ISSUE THREAD

**Issue by luckypoem** [jellehermsen/HasClunk#1]
hi,

i setup a blog : http://hc.smt.biz.st ,but how to paginate?

**Comment by jelliehermsen** [comment]
Great that you're using HasClunk! It doesn't have pagination atm. It simply uses archive pages that lists all the posts. You can pick the amount of posts shown on the home page by changing the config variable _posts_on_home_

If you really long for this feature, I could add it pretty easily.
